export enum NomeSetor {
  PRODUCAO      = "PRODUCAO",
  MANUTENCAO    = "MANUTENCAO",
  UTILIDADES    = "UTILIDADES",
  QUALIDADE     = "QUALIDADE",
  LOGISTICA     = "LOGISTICA",
  ADMINISTRATIVO = "ADMINISTRATIVO",
}